# Website settings
title: Abed Hadri dev
baseurl:  # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: http://localhost  # url should be 'http://<github_username>.github.io/homepage' as before
img_path: /static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before
